#!/bin/zsh
# Zsh Environment Config
# Nefari0uss

# shellcheck disable=SC1071
# Shellcheck doesn't work on zsh files.

unsetopt GLOBAL_RCS # Disable global zsh configs

#region Dedupe *PATH Environment Variables
# -U ensures each entry in these is unique by discarding duplicates.
unset MANPATH  # Unset to avoid interference from inherited environment
export -U cdpath PATH path FPATH fpath MANPATH manpath
export -UT INFOPATH infopath  # -T creates a "tied" pair.

# TODO - Make a function to let you view the tied pairs more easily.
# print -l $(typeset +U) | sort
#endregion

#region --- Base Environment Variables ---
export LC_ALL="en_US.UTF-8" # Overrides all other LC_* variables and LANG.
export LANGUAGE="en_US" # Sets the language priority.
export PAGER=bat
export EDITOR=vim
export VISUAL="${EDITOR}"
# export MANPAGER="sh -c 'col -bx | batcat -l man -p'"
# export MANROFFOPT="-c" # Fixes the weird characters in man pages.
export TZ="America/New_York"
export READNULLCMD="${PAGER}"

# GPG
# export GPG_TTY=$(tty)

#endregion

#region --- XDG Base Directory Specification ---
# https://wiki.archlinux.org/title/XDG_Base_Directory
# https://gist.github.com/roalcantara/107ba66dfa3b9d023ac9329e639bc58c

# XDG Base Directories
# User executables (e.g. custom scripts, user-installed binaries).
export XDG_BIN_HOME="${HOME}/.local/bin"
# Cached data (e.g. browser cache, pip cache).
export XDG_CACHE_HOME="${HOME}/.cache"
# Config files (e.g. app settings, dotfiles).
export XDG_CONFIG_HOME="${HOME}/.config"
# App data (e.g. icons, user databases).
export XDG_DATA_HOME="${HOME}/.local/share"
# Runtime files (e.g. sockets, temporary runtime data).
export XDG_RUNTIME_DIR="${HOME}/.xdg"
# State files (e.g. history, session state).
export XDG_STATE_HOME="${HOME}/.local/state"

# User Base Directories
# Desktop files (e.g. shortcuts, saved files).
export XDG_DESKTOP_DIR="${HOME}/Desktop"
# Documents (e.g. text files, PDFs).
export XDG_DOCUMENTS_DIR="${HOME}/Documents"
# Downloads (e.g. files from browsers).
export XDG_DOWNLOAD_DIR="${HOME}/Download"
# Music files (e.g. mp3, flac).
export XDG_MUSIC_DIR="${HOME}/Music"
# Pictures (e.g. jpg, png, screenshots).
export XDG_PICTURES_DIR="${HOME}/Pictures"
# Videos (e.g. mp4, mkv).
export XDG_VIDEOS_DIR="${HOME}/Videos"

mkdir -p ${XDG_BIN_HOME} ${XDG_CACHE_HOME} ${XDG_CONFIG_HOME} ${XDG_DATA_HOME} ${XDG_RUNTIME_DIR} ${XDG_STATE_HOME} ${XDG_VIDEOS_DIR}
#endregion

#region --- Zsh Specific Environment Variables ---

# Location of zsh config files.
ZDOTDIR="${XDG_CONFIG_HOME}/zsh"
ZSH_COMPDUMP="${XDG_CACHE_HOME}/zsh/.zcompdump"

# Max number of directories in pushd/popd stack.
DIRSTACKSIZE=25

# Zsh History
HIST_DIR="${XDG_STATE_HOME}/zsh"
if [[ ! -d "${HIST_DIR}" ]]; then
  mkdir -p "${HIST_DIR}";
fi

# Zsh history file.
export HISTFILE="${HIST_DIR}/zsh_history"
HISTFILESIZE=2000  # Max lines in history file.
HISTIGNORE="cls:clear:pwd:ls:cd:exit:csb:h:history:z:zi"  # Ignore these commands in history.
HISTSIZE=1000      # Max commands to keep in session.
SAVEHIST=1000      # Max commands to save to file (<= HISTSIZE).
#endregion

#region --- Core Utils ---
export CURL_HOME="${XDG_CONFIG_HOME}/curl"
export WGETRC="${XDG_CONFIG_HOME}/wget/wgetrc"

# Wget history file can only be set via the command line, not in the config file.
alias wget="wget --hsts-file=${XDG_DATA_HOME}/wget-hsts"

# Less
# 'i' - Search ignores case unless uppercase is used.
# 'm' - Show the percentage of the file displayed.
# 'r' - Display raw control characters.
# 's' - Squeeze blank lines into one.
# 'x' - Prevents less from clearing screen upon exit.
# 'F' - Automatically exit if content fits on one screen.
# 'M' - Like 'm' but more verbose.
# 'N' - Display line numbers. ('n' will suppress.)
# 'Q' - Turns off the terminal bell.
# 'R' - Like '-r' but only ANSI color escape sequences are shown.
# '~' - Show blank lines and not ~ at the end of the file.
# 'x#' - Number of spaces per tab.
# 'z-#' - The size of the window height minus the value.
# --mouse: Enables mouse input and scrolling.
# --no-histdups: Prevents duplicate entries in the history.
# --use-color: ...enables color.
# --save-marks: Saves marks between sessions.
export LESS="-isx -FMNQR -~ -x2 -z-4 --mouse --no-histdups --use-color --save-marks"
export LESSHISTFILE="${XDG_STATE_HOME}/less/history"
export LESSCHARSET="utf-8"

#endregion

#region --- Editors ---
export VIM_INIT="${XDG_CONFIG_HOME}/vim/vimrc"
export VIM_DOT_DIR="${XDG_CONFIG_HOME}/vim"
#endregion

#region --- Languages and Related Tooling ---

# Go-Lang
export GOBIN="${XDG_BIN_HOME}" # Go Binaries
export GOPATH="${XDG_DATA_HOME}/go" # Go Workspace
export GOMODACHE="${XDG_CACHE_HOME}/go/mod" # Go Module Cache

# Lua
export LUAROCKS_CONFIG="${XDG_CONFIG_HOME}/luarocks/config.lua"

# NodeJS / npm / pnpm
export NODE_REPL_HISTORY="${XDG_DATA_HOME}/node_repl_history"
export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME}/npm/npmrc"
export PNPM_HOME="${XDG_DATA_HOME}/pnpm"

# Python
export PYENV_ROOT="${XDG_DATA_HOME}/pyenv"
export PYENV_VIRTUALENV_ROOT="${XDG_DATA_HOME}/pyenv/versions"
export PYLINTHOME="${XDG_CACHE_HOME}/pylint"
export PYTHONUSERBASE="${XDG_DATA_HOME}/python"
export PYTHON_HISTORY="${XDG_STATE_HOME}/python/python_history"

# Python pip
export PIP_CONFIG_FILE="${XDG_CONFIG_HOME}/pip/pip.conf"
export PIP_CACHE_DIR="${XDG_CACHE_HOME}/pip"
export PIP_LOG_FILE="${XDG_STATE_HOME}/pip/pip.log"

# Java
# export JAVA_HOME="${XDG_DATA_HOME}/java"

# Ruby
export BUNDLE_USER_CACHE="${XDG_CACHE_HOME}/bundle"
export BUNDLE_USER_CONFIG="${XDG_CONFIG_HOME}/bundle"
export BUNDLE_USER_PLUGIN="${XDG_DATA_HOME}/bundle"
export GEM_HOME="${XDG_DATA_HOME}/gem"
export GEM_PATH="${GEM_HOME}:${GEM_PATH}"

# Rust
export CARGO_HOME="${XDG_DATA_HOME}/cargo"
export CARGO_TARGET_DIR="${XDG_DATA_HOME}/cargo/target"
export RUSTUP_HOME="${XDG_DATA_HOME}/rustup"
#endregion

#region --- General Tools ---

# Android
export ANDROID_HOME="${XDG_DATA_HOME}/android"
export ANDROID_USER_HOME="${XDG_DATA_HOME}/android"
export ANDROID_AVD_HOME="${XDG_DATA_HOME}/android/avd"

# Bat
export BATPIPE=color
export BATDIFF_USE_DELTA=true

# DotNet Core
export DOTNET_CLI_HOME="${XDG_DATA_HOME}/dotnet"
export DOTNET_CLI_TELEMETRY_OPTOUT=1
export DOTNET_INTERACTIVE_CLI_TELEMETRY_OPTOUT=1

# Gimp
export GIMP2_DIRECTORY="${XDG_CONFIG_HOME}/gimp"

# Httpie
export HTTPIE_CONFIG_DIR="${XDG_CONFIG_HOME}/httpie"

# LaTeX / TexLive
export TEXMFHOME="${XDG_DATA_HOME}/texmf"
export TEXMFVAR="${XDG_CACHE_HOME}/texlive/texmf-var"
export TEXMFCONFIG="${XDG_CONFIG_HOME}/texlive/texmf-config"

TEXLIVE_ROOT="${HOME}/.local/texlive/2025"
TEXMF_MANPATH="${TEXLIVE_ROOT}/texmf-dist/doc/man"
TEXMF_INFOPATH="${TEXLIVE_ROOT}/texmf-dist/doc/info"
TEXMF_BINPATH="${TEXLIVE_ROOT}/bin/x86_64-linux"

# Lesspipe: https://github.com/wofr06/lesspipe
LESSOPEN="|lesspipe.sh %s";
export LESSOPE

# Moor
export MOOR="--reformat --tab-size=2"

# NB
export NB_DIR="${XDG_DATA_HOME}/nb"
export NBRC_PATH="${XDG_CONFIG_HOME}/nb/nbrc"

# RipGrep
export RIPGREP_CONFIG="${XDG_CONFIG_HOME}/ripgrep/config"

# Subversion
alias svn="svn --config-dir ${XDG_CONFIG_HOME}/subversion"

# TealDeer, aka TLDR
export TEALDEER_CONFIG_DIR="${XDG_CONFIG_HOME}/tealdeer"

# Zoxide
# https://github.com/ajeetdsouza/zoxide#configuration
export _ZO_DATA_DIR="${XDG_DATA_HOME}/zoxide" # Where the db is stored.
export _ZO_ECHO_PATH="1" # Echo the path upon execution.
# export _ZO_EXCLUDE_DIRS="${HOME}:${HOME}/private" # Exclude directories for zoxide.
export _ZO_RESOLVE_SYMLINKS="1" # Resolve symlinks before adding a dir to the db.
#endregion

#region --- Testing Tools ---
export CYPRESS_INSTALL_BIN=0
export PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
export PUPPETEER_SKIP_DOWNLOAD=true
#endregion

#region --- Analytics and Telemetry ---
# Do Not Track - https://www.consoledonottrack.com
export DO_NOT_TRACK=1
export NUXT_TELEMETRY_DISABLED=1
export POWERSHELL_TELEMETRY_OPTOUT=1
export HOMEBREW_NO_ANALYTICS=1
#endregion

#region --- PATH ---
path=(
  "${XDG_BIN_HOME}"
  ./node_modules/.bin
  "${PNPM_HOME}"
  "${PYENV_ROOT}/bin"
  "${CARGO_HOME}/bin"
  "${HOME}/.luarocks/bin"
  $TEXMF_BINPATH
  /usr/local/bin
  /usr/local/sbin
  /usr/bin
  /usr/sbin
  /bin
  /sbin
  $path
)
#endregion

#region --- FPATH ---
fpath=(
  "${ZDOTDIR}/functions"
  "${XDG_DATA_HOME}/zsh/site-functions"(N)
  $fpath
)
#endregion

#region --- MANPATH ---

# This seems to cause problems with $MANPATH
# manpath=(
#   $(manpath -g)
#   $TEXMF_MANPATH
# )

manpath=(
  "${(@s/:/)$(manpath -g)}" # Assign system manpaths (split on :)
  "${XDG_DATA_HOME}/man"
  "$TEXMF_MANPATH"
)

# Start with system manpath, then append custom paths
# if command -v manpath >/dev/null 2>&1; then
#   export MANPATH="$(manpath -g):${TEXMF_MANPATH}"
# else
#   export MANPATH="/usr/share/man:/usr/local/share/man:${TEXMF_MANPATH}"
# fi
#endregion

#region --- INFOPATH ---
infopath=(
  $infopath
  $TEXMF_INFOPATH
)
#endregion

# Define environment for non-login, non-interactive shells which don't source .zprofile.
# SHLVL is the shell level. Each nested terminal level increments this by 1.
# if [[ ("$SHLVL" -eq 1) && ! -o "${ZDOTDIR}/.zprofile" ]]; then
#   print "Non-login, non-interactive shell detected. Sourcing .zprofile."
#   source "${ZDOTDIR}/.zprofile"
# fi
