# LSD Configuration File.

classic: false  # Disable classic ls-compatible mode.

blocks:  # Columns for long and tree layouts.
 - permission
 # - user
 # - group
 - size
 - date
 - name
 - git

color:
  when: auto  # Auto choose whether to colorize output.
  theme: default  # Use the default color theme.

date: date  # Show full date format.

dereference: false  # Do not dereference symbolic links.

display:
  all  # Show all items.

icons:
  when: auto  # Show icons automatically.
  theme: fancy  # Use the fancy icon theme.
  separator: " "  # Separate icon and name with a single space.

indicators: false  # Do not show indicator characters.

layout: grid  # Use grid layout.

recursion:
  enabled: false  # Disable recursive listing.

permission: rwx  # Show permissions in rwx format.

sorting:
  column: name  # Sort entries by name.
  dir-grouping: first  # Put directories before files.
  reverse: false  # Do not reverse sort order.

no-symblink: false  # Show symlink targets (note: key uses non-standard spelling).

total-size: false  # Do not display total directory sizes.

hyperlink: never  # Do not add hyperlinks to filenames.

symblink-arrow: ⇒  # Use '⇒' to point from symlink to target.

header: false  # Do not show block headers.

literal: false  # Do not quote filenames.

truncate-owner:
  after:  # No truncation of owner/group names.
  marker: ""  # No marker appended when truncating.
