#!/bin/bash

# https://gist.github.com/roalcantara/107ba66dfa3b9d023ac9329e639bc58c
# https://github.com/dirs-dev/directories-jvm

export XDG_BIN_HOME="${HOME}/.local/bin"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_DESKTOP_DIR="${HOME}/desktop"
export XDG_DOCUMENTS_DIR="${HOME}/documents"
export XDG_DOWNLOAD_DIR="${HOME}/download"
export XDG_MUSIC_DIR="${HOME}/music"
export XDG_PICTURES_DIR="${HOME}/pictures"
export XDG_RUNETIME_DIR="${HOME}/.xdg"
export XDG_STATE_HOME="${HOME}/.local/state"
export XDG_VIDEOS_DIR="${HOME}/videos"


# TODO Look up
# export PKG_CONFIG_PATH
export NVIM_APPNAME="${XDG_CONFIG_HOME}/nvim"
export CARGO_HOME="${XDG_DATA_HOME}/cargo"
export CURL_HOME="${XDG_CONFIG_HOME}/curl"
export GNUPGHOME="${XDG_CONFIG_HOME}/gnupg"
export GOPATH="${XDG_DATA_HOME}/go"
export HISTFILE="${XDG_STATE_HOME}/zsh/history"
export HTTPIE_CONFIG_DIR="${XDG_CONFIG_HOME}/httpie"
export LESSHISTFILE="${XDG_DATA_HOME}/less/history"
export LUAROCKS_CONFIG="${XDG_CONFIG_HOME}/luarocks/config.lua"
export NPM_CONFIG_CACHE="${XDG_CACHE_HOME}/npm"
export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME}/npm/npmrc"
export PYENV_ROOT="${XDG_DATA_HOME}/pyenv"
export PYENV_VIRTUALENV_ROOT="${XDG_DATA_HOME}/pyenv/versions"
export PYLINTHOME="${XDG_CACHE_HOME}/pylint"
export RIPGREP_CONFIG="${XDG_CONFIG_HOME}/ripgrep/config"
export RIPGREP_CONFIG_PATH="${XDG_CONFIG_HOME}/ripgrep/ripgreprc"
export RUSTUP_HOME="${XDG_DATA_HOME}/rustup"
export TEALDEER_CONFIG_DIR="${XDG_CONFIG_HOME}/tealdeer"
export TERMINFO="${XDG_DATA_HOME}/terminfo"
# export TERMINFO_DIRS="${XDG_DATA_HOME}/terminfo"
export TERMINFO_DIRS=${TERMINFO_DIRS}:${TERMINFO}:/usr/share/terminfo
export WGETRC="${XDG_CONFIG_HOME}/wgetrc"


# export NPM_PACKAGES="$HOME/Executables/npm"
# export PNPM_HOME="$NPM_PACKAGES/bin"
