#!/bin/bash


# Less Configuration Section

# Sets the active options for 'less':
# 'F' - Automatically exits if the content can be displayed on one screen.
# 'R' - Allows raw control characters to be displayed.
# 'X' - Prevents 'less' from clearing the screen upon exit.
# 'Q' - Reduces the verbosity of the bell sound.
export LESS='FRXQ'

# Specifies the character encoding for 'less' to be UTF-8, ensuring proper display of UTF-8 encoded text.
export LESSCHARSET='UTF-8'

# Disables the history file for 'less', meaning search patterns and commands won't be saved between sessions.
export LESSHISTFILE='-'

# Configures the command that 'less' will use to invoke an editor when the 'v' command is used within 'less'.
# It utilizes the environment variable $EDITOR as the preferred editor, and passes specific flags to jump to the relevant line of the file being viewed.
export LESSEDIT="$EDITOR ?lm+%lm. %f"

# Highlight section titles in manual pages.
export LESS_TERMCAP_md="${yellow}";
