#!/bin/zsh
# ZShell Config
# Nefari0uss

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.config/zsh/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# This setting ensures that Zsh's compfix security checks are not disabled.
# Compfix performs security checks on directories in your $PATH and completion directories to prevent
# privilege escalation attacks. Setting this to FALSE activates these checks, enhancing security.
ZSH_DISABLE_COMPFIX=FALSE

# This enables Zsh's command correction feature.
ENABLE_CORRECTION=TRUE

# Makes Zsh display a series of waiting dots while it is generating command completions that take a noticeable amount of time.
COMPLETION_WAITING_DOTS=TRUE

# This is used so many times that may as well put it here, before everything else.
# Enable additional glob operators.
# setopt EXTENDED_GLOB

# autoload -Uz compinit promptinit vcs_info: This line uses the `autoload` command to mark the functions
# `compinit`, `promptinit`, and `vcs_info` for lazy loading. The `-Uz` flags are used to avoid alias
# expansion and ensure the functions are loaded in the current shell. `compinit` initializes shell
# completion, `promptinit` initializes prompt themes, and `vcs_info` provides version control information.

autoload -Uz compinit promptinit vcs_info
# compinit -d "${ZSH_CACHE_DIR}/zcompdump-${ZSH_VERSION}"
# promptinit # Initializes the prompt system, allowing the use of themes and custom prompts.

bindkey -v  # Enable Vi mode for key bindings.

# function zle-keymap-select {
#     case $KEYMAP in
#         vicmd)      MODE="NORMAL";;
#         main|viins) MODE="INSERT";;
#     esac
#     zle reset-prompt
# }
# MODE="INSERT"
# autoload -Uz add-zsh-hook
# add-zsh-hook zle-keymap-select zle-keymap-select
# PROMPT='[%{$fg_bold[green]%}$MODE%{$reset_color%}] %~ %# '

() {
  local file=
  for file in "${ZDOTDIR}/rc.d"/<->-*.zsh(n); do
    source $file   # `.` is like `source`, but doesn't search your $path.
  done
} "$@"


# TODO - Move these to dedicated files and lazy-load them.

cls () {
  clear
  printf '\033[3J'
}

groot () {
  local root_dir
  root_dir=$(git rev-parse --show-toplevel 2>/dev/null) || {
    echo "Not in a git repository."
    return 1
  }
  cd "$root_dir" || return
}

# broot?


# Tig
# mkdir ${XDG_CONFIG_HOME}/tig/config
# mkdir -p ${XDG_STATE_HOME}/tig

# bun completions
# [ -s "/home/nefari0uss/.bun/_bun" ] && source "/home/nefari0uss/.bun/_bun"

# To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
[[ ! -f ~/.config/zsh/.p10k.zsh ]] || source ~/.config/zsh/.p10k.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
